csrutil authenticated-root disable;
diskutil mount /Volumes/macos;
 Mount -uv /Volumes/macos;
 cd /Volumes/macos/System/Library/LaunchAgents;
mkdir tmp;
mv com.apple.ManagedClientAgent.* tmp/;
mv com.apple.mdmclient.* tmp/;
cd ../LaunchDaemons;
mkdir tmp;
mv com.apple.ManagedClient.* tmp/;
mv com.apple.mdmclient.* tmp/;
bless --folder /Volumes/macos/System/Library/CoreServices --bootefi --create-snapshot;
